export const FRANCHISE_PROPERTY_PROMOTION_LABELS: Readonly<Record<string, string>> = {
    status: '물건 상태',
    operationType: '운영 구분',
    operation_type: '운영 구분',
    processStatus: '진행 상태',
    category: '업종',
    categoryMajor: '업태(대분류)',
    categoryMiddle: '업종(중분류)',
    categorySmall: '업종(소분류)',
    industry: '업종',
    desiredBusinessType: '희망 업태(대분류)',
    desiredCategory: '희망 업종(중분류)',
    desiredBrand: '입점 희망 브랜드',
    matchPriority: '우선순위',
    industryCategory: '업종 대분류',
    industrySector: '업종 중분류',
    industryDetail: '업종 상세',
    detailAddress: '상세 주소',
    propertyRegion: '주소 지역',
    roadAddress: '도로명 주소',
    jibunAddress: '지번 주소',
    zoneNo: '우편번호',
    propertyName: '물건명',
    propertyAddress: '물건 주소',
    locationMemo: '입지 메모',
    area: '면적',
    privateArea: '전용면적',
    privateAreaInput: '전용면적 입력값',
    privateAreaUnit: '전용면적 입력 단위',
    privateAreaSquareMeter: '전용면적 ㎡',
    privateAreaPyeong: '전용면적 평',
    supplyArea: '공급면적',
    floor: '층수',
    totalFloors: '전체 층수',
    parkingAvailable: '주차 가능 여부',
    currentStatus: '현재 상태',
    currentFloor: '해당층',
    totalFloor: '전체층',
    parking: '주차',
    featureMemo: '특징 메모',
    overviewMemo: '개요 메모',
    deposit: '보증금',
    premium: '권리금',
    monthlyRent: '월세',
    maintenance: '관리비',
    maintenanceFee: '관리비',
    vatIncluded: '부가세 포함 여부',
    leaseAvailableDate: '임대 가능일',
    contractPeriod: '계약 기간',
    negotiable: '협의 가능 여부',
    rentFreeAvailable: '렌트프리 가능 여부',
    rentFreePeriod: '렌트프리 가능 기간',
    interiorSupportAvailable: '인테리어 지원 가능 여부',
    simpleInstallSupportAvailable: '간판 설치 지원 가능 여부',
    facilityWorkNegotiable: '시설 공사 협의 가능 여부',
    landlordSupportMemo: '기타 지원 내용',
    consultationMemo: '상담 메모',
    riskMemo: '리스크 메모',
    nextAction: '다음 액션',
    nextContactAt: '다음 연락 예정일',
    fileNames: '등록 파일',
    fileAttachments: '첨부 파일',
    totalPrice: '총 금액',
    monthlyRevenue: '월매출',
    monthlyProfit: '월순수익',
    yieldPercent: '수익률',
    franchiseBrand: '프랜차이즈 브랜드',
    recommendedBusiness: '추천 업종',
    memo: '메모'
} as const;

export const FRANCHISE_PROPERTY_PROMOTION_MAPPED_KEYS = new Set([
    'id',
    'companyName',
    'companyId',
    'company_id',
    'managerId',
    'manager_id',
    'managerName',
    'name',
    'propertyName',
    'address',
    'propertyAddress',
    'region',
    'sido',
    'sigungu',
    'latitude',
    'longitude',
    'lat',
    'lng',
    'coordinates',
    'createdAt',
    'updatedAt',
    'isFavorite',
    'sourceType',
    'brand',
    'desiredBrand',
    'fileAttachments',
    'fileNames',
    'sourcePropertySnapshot'
]);

export const FRANCHISE_PROPERTY_PROMOTION_HEAVY_KEYS = new Set([
    'photos',
    'files',
    'documents',
    'revenueHistory',
    'operationCustomFields',
    'leaseCustomFields',
    'promotedCustomers'
]);
